### ISSUE TITLE
预训练模型

### ISSUE THREAD

**Issue by xujiao3628** [amoshyc/siamRPN#1]
你好，预训练模型可以放出来吗？谢谢你哦

**Comment by amoshyc** [comment]
呃…這不是 [官方](https://github.com/foolwood/DaSiamRPN) 的 repo 啊，我也只是在複現中

**Comment by xujiao3628** [comment]
> 呃...这不是[官方](https://github.com/foolwood/DaSiamRPN)的repo啊，我也只是在复现中

你放出来的那个训练有问题是吗？

**Comment by amoshyc** [comment]
對，還訓練不起來

**Comment by xujiao3628** [comment]
> 对，还训练不起来

好的，我会关注这个工程的，谢谢你哦！

**Comment by xujiao3628** [comment]
> 對，還訓練不起來

https://github.com/MathsXDC/DaSiamRPNWithOfflineTraining
我看这个工程挺多STAR 我还没试，你可以看下有没有参考价值？嘿嘿

**Comment by amoshyc** [comment]
看起來很不錯喔，感謝
